spring:
  datasource:
    url: jdbc:h2:mem:fabanking
    username: fabanking
    password: f4b4nk1ng
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  main:
    allow-circular-references: true

fabrik:
  client:
    baseUrl: "https://sandbox.platfr.io/api/gbs/banking/v4.0/accounts"
    authSchema: "S2S"
    apiKey: "FXOVVXXHVCPVPBZXIJOBGUGSKHDNFRRQJP"
